-- Jalankan sekali di Supabase SQL Editor.
-- Memperkuat persetujuan Guru, klaim NIS Orang Tua, dan audit keamanan akun.

create table if not exists public.account_security_events (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users(id) on delete set null,
  target_user_id uuid references auth.users(id) on delete set null,
  event_type text not null,
  status text not null check (status in ('success', 'failed', 'blocked')),
  request_fingerprint text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists account_security_events_created_idx
  on public.account_security_events (created_at desc);
create index if not exists account_security_events_actor_idx
  on public.account_security_events (actor_user_id, created_at desc);
create index if not exists account_security_events_target_idx
  on public.account_security_events (target_user_id, created_at desc);

alter table public.account_security_events enable row level security;
revoke all on public.account_security_events from anon, authenticated;

-- Role tidak boleh lagi dibuat hanya berdasarkan user_metadata yang dapat
-- diubah sendiri oleh pengguna. Hanya app_metadata dari endpoint server/Admin
-- yang boleh menjadi sumber role aktif.
drop policy if exists "Users can create own role" on public.user_roles;
create policy "Approved users can create own assigned role"
on public.user_roles for insert to authenticated
with check (
  user_id = (select auth.uid())
  and email = (select auth.jwt() ->> 'email')
  and role in ('guru', 'orang_tua')
  and role = (select auth.jwt() -> 'app_metadata' ->> 'role')
  and (select auth.jwt() -> 'app_metadata' ->> 'approval_status') = 'approved'
);
drop policy if exists "Users can update own role" on public.user_roles;
create policy "Approved users can update own assigned role"
on public.user_roles for update to authenticated
using (user_id = (select auth.uid()))
with check (
  user_id = (select auth.uid())
  and email = (select auth.jwt() ->> 'email')
  and role in ('guru', 'orang_tua')
  and role = (select auth.jwt() -> 'app_metadata' ->> 'role')
  and (select auth.jwt() -> 'app_metadata' ->> 'approval_status') = 'approved'
);

-- Jika data lama sudah menghubungkan satu siswa ke beberapa akun, pertahankan
-- hubungan aktif yang paling baru dan arsipkan sisanya.
with ranked_links as (
  select
    parent_id,
    row_number() over (
      partition by student_id
      order by updated_at desc, created_at desc, parent_id
    ) as position
  from public.parent_student_links
  where status = 'active'
)
update public.parent_student_links as links
set status = 'inactive', updated_at = now()
from ranked_links
where links.parent_id = ranked_links.parent_id
  and ranked_links.position > 1;

create unique index if not exists parent_student_links_one_active_parent_idx
  on public.parent_student_links (student_id)
  where status = 'active';

-- Klaim NIS kini hanya boleh melalui endpoint server yang menerapkan rate
-- limit dan audit. RPC lama ditutup agar pembatasan tidak dapat dilewati.
do $$
begin
  if exists (
    select 1
    from pg_proc
    join pg_namespace on pg_namespace.oid = pg_proc.pronamespace
    where pg_namespace.nspname = 'public'
      and pg_proc.proname = 'claim_parent_student_by_nis'
  ) then
    execute
      'revoke all on function public.claim_parent_student_by_nis(text) from public, anon, authenticated';
  end if;
end
$$;

notify pgrst, 'reload schema';
